"""Canonical content APIs for authoring validation and compiled runtime lookup."""

from .hashes import (
    canonical_json_bytes,
    normalize_markdown,
    normalized_semantic_hash,
    source_tree_hash,
)
from .injection import (
    MAX_INJECTION_ESTIMATED_TOKENS,
    AssembledInstruction,
    InjectionAssemblyError,
    InjectionLocale,
    ProjectionInstructionAssembler,
    assemble_canonical_instruction,
    assemble_requested_locale_instruction,
    estimate_injection_tokens,
    resolve_injection_locale,
    resolve_prompt_locale,
    resolve_requested_injection_locale,
    validate_candidate_instruction,
)
from .loader import (
    ContentLoader,
    ReasoningContentProjectionLoader,
    load_compiled_bundle,
    load_reasoning_content_projections,
)
from .manifest import build_content_bundle, policy_digests, serialize_bundle
from .method import (
    PROCEDURE_HEADINGS,
    build_reasoning_content_projections,
    compile_method,
    compile_method_content_projections,
    complement_fragment,
    validate_cases,
    validate_procedure,
)
from .schema import (
    AUTHORING_SCHEMA,
    BUNDLE_SCHEMA,
    CASES_SCHEMA,
    COMPILED_METHOD_SCHEMA,
    FROZEN_FAMILIES,
    FROZEN_METHOD_FAMILIES,
    FROZEN_METHOD_IDS,
    FROZEN_ROUTING,
    INJECTABLE_REASONING_CONTENT_SCHEMA,
    REASONING_CONTENT_PROJECTIONS_SCHEMA,
    SELECTION_CATALOG_SCHEMA,
    ContentValidationError,
    validate_catalog,
    validate_compiled_bundle_shape,
    validate_method_authoring,
    validate_reasoning_content_projections_shape,
    validate_routing_policy,
)

__all__ = [
    "AUTHORING_SCHEMA",
    "AssembledInstruction",
    "BUNDLE_SCHEMA",
    "CASES_SCHEMA",
    "COMPILED_METHOD_SCHEMA",
    "ContentLoader",
    "ContentValidationError",
    "FROZEN_FAMILIES",
    "FROZEN_METHOD_FAMILIES",
    "FROZEN_METHOD_IDS",
    "FROZEN_ROUTING",
    "INJECTABLE_REASONING_CONTENT_SCHEMA",
    "InjectionAssemblyError",
    "InjectionLocale",
    "MAX_INJECTION_ESTIMATED_TOKENS",
    "PROCEDURE_HEADINGS",
    "REASONING_CONTENT_PROJECTIONS_SCHEMA",
    "ReasoningContentProjectionLoader",
    "SELECTION_CATALOG_SCHEMA",
    "ProjectionInstructionAssembler",
    "assemble_canonical_instruction",
    "assemble_requested_locale_instruction",
    "build_content_bundle",
    "build_reasoning_content_projections",
    "canonical_json_bytes",
    "compile_method",
    "compile_method_content_projections",
    "complement_fragment",
    "load_compiled_bundle",
    "load_reasoning_content_projections",
    "normalize_markdown",
    "normalized_semantic_hash",
    "policy_digests",
    "serialize_bundle",
    "source_tree_hash",
    "estimate_injection_tokens",
    "resolve_injection_locale",
    "resolve_requested_injection_locale",
    "resolve_prompt_locale",
    "validate_candidate_instruction",
    "validate_catalog",
    "validate_cases",
    "validate_compiled_bundle_shape",
    "validate_method_authoring",
    "validate_reasoning_content_projections_shape",
    "validate_procedure",
    "validate_routing_policy",
]
